### ISSUE TITLE
Doubt: Regarding Configuration file for settings of the models

### ISSUE THREAD

**Issue by User-DK** [seldon-code/pyseldonlib#1]
While Creating bindings are we just going to rely on Config (toml) file or Is there anything I am missing.
Also if we pass in arguments as inputs instead of config file then there might be some structural changes to the code I guess.
Also the optional networks.txt and agents.txt needs to be clarified are we again going to rely on txt files in python ? 

Please correct me if I missunderstood something!

**Comment by HaoZeke** [comment]
@User-DK, good question.

My thoughts were that the approach here is to make progressively complex bindings. The first pass will be a thin wrapper to C++ driver and once that works, then more of the underlying functions called by the C++ driver will be bound.

It is only at this second stage can we (as an example) drop the loading logic in C++ since we will wrap the functions called directly and so the arguments can then be constructed in Python, either by loading (via `tomli/toml`) configuration files or just by directly constructing arguments in a `.py` file.

Similar arguments will apply to the `.txt` files for now.

cc @MSallermann @amritagos for more thoughts / comments
